import { Roboto } from 'next/font/google'; // Roboto fontunu import et
import Header from "@/components/common/Header/Header";
import "../style/globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header/>
      <body className={`antialiased ${roboto.className}`}>
        {children}
      </body>
    </html>
  );
}
